### ISSUE TITLE
Cmake configures too long

### ISSUE THREAD

**Issue by tort-dla-psa** [caseymcc/HastyNoise#15]
Mainly because of hunter which constantly downloads something. I have good internet connection, but compiling this repo took something like ~5 minutes. It would be great if there was an option to skip all hunter stuff

**Comment by caseymcc** [comment]
Its should be a one time event, the first time you run cmake. After that this is only a minor <5s check to verify everything is there.

Also without all the hunter stuff it would not compile. Hunter is downloading and compiling all the libs (that is what takes time) otherwise I would have to include all the information to compile the 3rd party libraries, link them and make sure the are no inconsistencies with your local machine. That would take you way more time the 5 mins to handle the third party items.

**Comment by tort-dla-psa** [comment]
Ah, okay then, thanks
